# Generated by Django 5.2.8 on 2025-11-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
